/********************************************
 * Project name: IFJ - projekt
 * File: bin_tree.h
 * Date: 23. 09. 2021
 * Last change: 23. 09. 2021
 * Team: TODO
 * Authors:  Aliaksandr Skuratovich
 *           Evgeny Torbin
 *           Lucie Svobodová
 *           Jakub Kuzník
 *******************************************/
/**
 *
 *
 *  @package bin_tree
 *  @file bin_tree.h
 *  @brief Headers for bin_tree.c
 *
 *
 *
 *  @author Aliaksandr Skuratovich
 *  @author Evgeny Torbin
 *  @author Lucie Svobodová
 *  @author Jakub Kuzník
 */

// WAAAAAAAAAAAAAAAAAARRRRRRRRRRRRRNIIIIIIIIIIIIIIIINGGGGGGGGGGG
// SAŠO NEIMPLEMENTUJ NIC :SMRCKABAT:


#pragma once

// Includes
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <assert.h>
#include <ctype.h>
#include <math.h>
#include <stdint.h>
#include "debug.h"
#include "sym_table_macros.h"
#include "scanner.h"
#include "errors.h"
//

/**
 * In binary tree we store table of symbols.
 * Each identificator has field of validity. If not GTS identificator is generated by function asci value.
 *      GTS - global table of symbols - has Highest priority
 *                                    - It is for Global variables and functions
 *      LTS - local table of symbols - each function or for has this
 *
 * In functions we have some validity levels. Smaller number means higher level.
 *
 */
typedef struct data {
    string i_name;          /**< Identificator name. Could be name of function or variable.*/
    unsigned int asci_val;  /**< Sum of i_name characters in asci values. */
    char type;              /**< Type of identificator could be FUNCTION or VARIABLE */
    unsigned int validity_field; /**< Highest is GTS. If not GTS them Function Asci value.*/
    unsigned int validity_level; /**< If we are in functions there are Validity levels. Smaller number means higher level starts on 0..*/



    //TODO FIND OUT HOW TO STORE FUNCTIONS PARAMS, RETURN VALUES ... WE DONT NEED THIS INFO IF type=VARIABLE...
    //TODO if variable store data_type
    //Harmin hase some kind of dynamic recognization.

} data;


/**
 * Binary tree structure. each node has pointer to two child nodes left and right.
 * Each node can have 0-2 child node.
 * Each node has just one parent.
 *
 * .data has to be more them .left child .data
 * .data has to be less them .right child .data
 */
typedef struct node {
    struct data *data;   /**< Data stored in node.   */
    struct node *l_child;       /**< Pointer to left side child.  */
    struct node *r_child;       /**< Pointer to right side child. */
} node;


/**
 * Each identificator has field of validity. If not GTS identificator is generated by function asci value.
 * GTS - global table of symbols - has Highest priority
 *      - It is for Global variables and functions
 *      LTS - local table of symbols - each function or for has this
 *
 * -In functions we have some validity levels. Smaller number means higher level.
 *
 */
typedef struct validity {
    char type;                   /**< Type of identificator could be FUNCTION or VARIABLE */
    unsigned int validity_field; /**< Highest is GTS. If not GTS them Function Asci value.*/
    unsigned int validity_level; /**< If we are in functions there are Validity levels. Smaller number means higher level starts on 0..*/
} validity;

/**
 * An interface to access scanner functions
 */
extern const struct tree_op_struct Tree;

struct tree_op_struct {
    void (*print_tree)();
    bool (*insert)(token_t *, validity);
    bool (*delete_node)(node *);
    bool (*free_tree)(node *);
    int (*get_string_asci)(string);
    bool (*create_tree)(node *, token_t *, validity);

};
