-- test case 49.
-- Description : no error, parsing definitions, declarations

-- Expected : '0'
require "ifj21" 
 global aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa : function(string) : string, string, string

function aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (str : string) : string, string, string

end 

 global arst : function(string,         integer,             number,       number,     integer, string)
function arst(str : string, ddd : integer, nummm : number, aaa : number, ii: integer, suka :string)
end 

