require "ifj21"


function main()
    local i : integer
    write("69\n")
    while 1 == 1 do
      local j : integer
      write(i,"\n")
      break
      while 3 == 2 do
        local j : integer
      break
        repeat    
    write(i,"\n")
          local j : integer
          if true then
          write(i,"\n")
            local j : integer
          elseif false then
            write(i,"\n")
            local j : integer
          elseif true then
            local j : integer
          else
            local j : integer
      break
          end
          write(i,"\n")
      break
        until 1 == 1
      break
      end
    end
    while 1 == 1 do
      write(i,"\n")
      while 3 == 2 do
        local j : integer
      break
      end
      break
    end
end
main()

