require "ifj21"

function main ()
    while 1 == 1 do
	write("helo\n")
    for i = 0, 10, 1 do
	write("helo\n")
        for i = 0, 2, 2 do
	write("helo\n")
            if 1 == 6 then
                local k : integer = 1
            elseif 1 == 2 then
	write("helo\n")
                local j : number
            elseif 2 == 5 then
	write("helo\n")
                local c : string = "heyo"
            else
	write("helo\n")
                local m : integer = 9
                if 1 == 1 then
                    local k : integer = 3
                end
                repeat
	write("helo\n")
                    local z : string = "good"
                    break
                until 1 == 3
            end
            break
        end
        break
    end
    break
    end
	write("helo\n")
end

main()

